SNOWFLAKE_CONN_ID = 'snowflake_conn'
LOCAL_FILE_PATH = '/opt/airflow/data/Airline_Dataset.csv'

DB_NAME = 'AIRLINE_DWH'
SCHEMA_RAW = 'RAW'
SCHEMA_CORE = 'CORE'
SCHEMA_MARTS = 'MARTS'

STAGE_NAME = f'{DB_NAME}.{SCHEMA_RAW}.AIRLINE_FLIGHTS_STAGE'
RAW_TABLE = f'{DB_NAME}.{SCHEMA_RAW}.AIRLINE_FLIGHTS_RAW'
FILE_FORMAT = f'{DB_NAME}.{SCHEMA_RAW}.CSV_SKIP_HEADER'

PROC_LOAD_CORE = f'{DB_NAME}.{SCHEMA_CORE}.LOAD_CORE_LAYER'
PROC_LOAD_MARTS = f'{DB_NAME}.{SCHEMA_MARTS}.LOAD_MARTS_LAYER'