CREATE DATABASE IF NOT EXISTS AIRLINE_DWH;
USE DATABASE AIRLINE_DWH;

CREATE SCHEMA IF NOT EXISTS RAW;
CREATE SCHEMA IF NOT EXISTS CORE;
CREATE SCHEMA IF NOT EXISTS MARTS;

CREATE OR REPLACE FILE FORMAT AIRLINE_DWH.RAW.CSV_SKIP_HEADER
    TYPE = 'CSV'
    FIELD_DELIMITER = ','
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    NULL_IF = ('NULL', 'null', '');

CREATE OR REPLACE TRANSIENT TABLE AIRLINE_DWH.RAW.AIRLINE_FLIGHTS_RAW (
    "CSV_Row_Index" VARCHAR,
    "Passenger ID" VARCHAR,
    "First Name" VARCHAR,
    "Last Name" VARCHAR,
    "Gender" VARCHAR,
    "Age" VARCHAR,
    "Nationality" VARCHAR,
    "Airport Name" VARCHAR,
    "Airport Country Code" VARCHAR,
    "Country Name" VARCHAR,
    "Airport Continent" VARCHAR,
    "Continents" VARCHAR,
    "Departure Date" VARCHAR,
    "Arrival Airport" VARCHAR,
    "Pilot Name" VARCHAR,
    "Flight Status" VARCHAR,
    "Ticket Type" VARCHAR,
    "Passenger Status" VARCHAR
);

CREATE OR REPLACE STAGE AIRLINE_DWH.RAW.AIRLINE_FLIGHTS_STAGE
    FILE_FORMAT = AIRLINE_DWH.RAW.CSV_SKIP_HEADER;

CREATE OR REPLACE STREAM AIRLINE_DWH.RAW.AIRLINE_FLIGHTS_STREAM
ON TABLE AIRLINE_DWH.RAW.AIRLINE_FLIGHTS_RAW;

USE SCHEMA AIRLINE_DWH.CORE;

CREATE OR REPLACE TABLE AUDIT_LOG (
    LOG_ID NUMBER IDENTITY(1,1) PRIMARY KEY,
    LOG_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PROCEDURE_NAME VARCHAR,
    LAYER_NAME VARCHAR,
    ROWS_AFFECTED NUMBER,
    STATUS VARCHAR,
    MESSAGE VARCHAR
);

CREATE OR REPLACE TABLE PASSENGERS (
    PASSENGER_ID VARCHAR PRIMARY KEY,
    FIRST_NAME VARCHAR,
    LAST_NAME VARCHAR,
    GENDER VARCHAR,
    AGE NUMBER,
    NATIONALITY VARCHAR,
    LOADED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE AIRPORTS (
    AIRPORT_ID NUMBER IDENTITY(1,1) PRIMARY KEY,
    AIRPORT_NAME VARCHAR,
    COUNTRY_CODE VARCHAR,
    COUNTRY_NAME VARCHAR,
    CONTINENT VARCHAR,
    LOADED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE PILOTS (
    PILOT_ID NUMBER IDENTITY(1,1) PRIMARY KEY,
    PILOT_NAME VARCHAR,
    LOADED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE FLIGHTS (
    FLIGHT_ID NUMBER IDENTITY(1,1) PRIMARY KEY,
    PASSENGER_ID VARCHAR,
    AIRPORT_ID NUMBER,
    PILOT_ID NUMBER,
    DEPARTURE_DATE DATE,
    ARRIVAL_AIRPORT_CODE VARCHAR,
    FLIGHT_STATUS VARCHAR,
    TICKET_TYPE VARCHAR,
    PASSENGER_STATUS VARCHAR,
    LOADED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    FOREIGN KEY (PASSENGER_ID) REFERENCES PASSENGERS(PASSENGER_ID),
    FOREIGN KEY (AIRPORT_ID) REFERENCES AIRPORTS(AIRPORT_ID),
    FOREIGN KEY (PILOT_ID) REFERENCES PILOTS(PILOT_ID)
);

CREATE OR REPLACE PROCEDURE AIRLINE_DWH.CORE.LOAD_CORE_LAYER()
RETURNS VARCHAR
LANGUAGE SQL
AS
$$
DECLARE
    rows_inserted INTEGER DEFAULT 0;
BEGIN
    IF (SYSTEM$STREAM_HAS_DATA('AIRLINE_DWH.RAW.AIRLINE_FLIGHTS_STREAM') = FALSE) THEN
        RETURN 'No new data in stream. Skipped.';
    END IF;

    BEGIN TRANSACTION;

    MERGE INTO AIRLINE_DWH.CORE.PASSENGERS T
    USING (
        SELECT DISTINCT "Passenger ID", "First Name", "Last Name", "Gender", TRY_TO_NUMBER("Age") as Age, "Nationality"
        FROM AIRLINE_DWH.RAW.AIRLINE_FLIGHTS_STREAM
        WHERE METADATA$ACTION = 'INSERT'
    ) S
    ON T.PASSENGER_ID = S."Passenger ID"
    WHEN MATCHED THEN UPDATE SET
        T.FIRST_NAME = S."First Name",
        T.LAST_NAME = S."Last Name",
        T.UPDATED_AT = CURRENT_TIMESTAMP()
    WHEN NOT MATCHED THEN INSERT (PASSENGER_ID, FIRST_NAME, LAST_NAME, GENDER, AGE, NATIONALITY)
    VALUES (S."Passenger ID", S."First Name", S."Last Name", S."Gender", S.Age, S."Nationality");

    INSERT INTO AIRLINE_DWH.CORE.AIRPORTS (AIRPORT_NAME, COUNTRY_CODE, COUNTRY_NAME, CONTINENT)
    SELECT DISTINCT "Airport Name", "Airport Country Code", "Country Name", "Airport Continent"
    FROM AIRLINE_DWH.RAW.AIRLINE_FLIGHTS_STREAM
    WHERE "Airport Name" IS NOT NULL
      AND "Airport Name" NOT IN (SELECT AIRPORT_NAME FROM AIRLINE_DWH.CORE.AIRPORTS);

    INSERT INTO AIRLINE_DWH.CORE.PILOTS (PILOT_NAME)
    SELECT DISTINCT "Pilot Name"
    FROM AIRLINE_DWH.RAW.AIRLINE_FLIGHTS_STREAM
    WHERE "Pilot Name" IS NOT NULL
      AND "Pilot Name" NOT IN (SELECT PILOT_NAME FROM AIRLINE_DWH.CORE.PILOTS);

    INSERT INTO AIRLINE_DWH.CORE.FLIGHTS (PASSENGER_ID, AIRPORT_ID, PILOT_ID, DEPARTURE_DATE, ARRIVAL_AIRPORT_CODE, FLIGHT_STATUS, TICKET_TYPE, PASSENGER_STATUS)
    SELECT
        s."Passenger ID",
        a.AIRPORT_ID,
        p.PILOT_ID,
        TRY_TO_DATE(s."Departure Date", 'MM/DD/YYYY'),
        s."Arrival Airport",
        s."Flight Status",
        s."Ticket Type",
        s."Passenger Status"
    FROM AIRLINE_DWH.RAW.AIRLINE_FLIGHTS_STREAM s
    LEFT JOIN AIRLINE_DWH.CORE.AIRPORTS a ON s."Airport Name" = a.AIRPORT_NAME
    LEFT JOIN AIRLINE_DWH.CORE.PILOTS p ON s."Pilot Name" = p.PILOT_NAME
    WHERE s.METADATA$ACTION = 'INSERT';

    rows_inserted := SQLROWCOUNT;

    INSERT INTO AIRLINE_DWH.CORE.AUDIT_LOG (PROCEDURE_NAME, LAYER_NAME, ROWS_AFFECTED, STATUS, MESSAGE)
    VALUES ('LOAD_CORE_LAYER', 'CORE', :rows_inserted, 'SUCCESS', 'Batch loaded successfully');

    COMMIT;
    RETURN 'Success: Loaded ' || :rows_inserted || ' flights.';

EXCEPTION
    WHEN OTHER THEN
        ROLLBACK;
        INSERT INTO AIRLINE_DWH.CORE.AUDIT_LOG (PROCEDURE_NAME, LAYER_NAME, ROWS_AFFECTED, STATUS, MESSAGE)
        VALUES ('LOAD_CORE_LAYER', 'CORE', 0, 'FAILURE', SQLERRM);
        RETURN 'FAILURE: ' || SQLERRM;
END;
$$;

USE SCHEMA AIRLINE_DWH.MARTS;

CREATE OR REPLACE TABLE DAILY_COUNTRY_STATS (
    REPORT_DATE DATE,
    COUNTRY_NAME VARCHAR,
    TOTAL_FLIGHTS NUMBER,
    DELAYED_FLIGHTS NUMBER,
    UNIQUE_PASSENGERS NUMBER,
    LOADED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE PROCEDURE LOAD_MARTS_LAYER()
RETURNS VARCHAR
LANGUAGE SQL
AS
$$
BEGIN
    TRUNCATE TABLE AIRLINE_DWH.MARTS.DAILY_COUNTRY_STATS;

    INSERT INTO AIRLINE_DWH.MARTS.DAILY_COUNTRY_STATS (REPORT_DATE, COUNTRY_NAME, TOTAL_FLIGHTS, DELAYED_FLIGHTS, UNIQUE_PASSENGERS)
    SELECT
        f.DEPARTURE_DATE,
        a.COUNTRY_NAME,
        COUNT(f.FLIGHT_ID) AS TOTAL_FLIGHTS,
        COUNT(CASE WHEN f.FLIGHT_STATUS = 'Delayed' THEN 1 END) AS DELAYED_FLIGHTS,
        COUNT(DISTINCT f.PASSENGER_ID) AS UNIQUE_PASSENGERS
    FROM AIRLINE_DWH.CORE.FLIGHTS f
    JOIN AIRLINE_DWH.CORE.AIRPORTS a ON f.AIRPORT_ID = a.AIRPORT_ID
    GROUP BY 1, 2;

    INSERT INTO AIRLINE_DWH.CORE.AUDIT_LOG (PROCEDURE_NAME, LAYER_NAME, ROWS_AFFECTED, STATUS, MESSAGE)
    VALUES ('LOAD_MARTS_LAYER', 'MARTS', SQLROWCOUNT, 'SUCCESS', 'Marts refreshed');

    RETURN 'Success: Marts Loaded';
END;
$$;

CREATE TABLE AIRLINE_DWH.CORE.FLIGHTS_HISTORY_DEMO CLONE AIRLINE_DWH.CORE.FLIGHTS;
UPDATE AIRLINE_DWH.CORE.FLIGHTS_HISTORY_DEMO SET FLIGHT_STATUS = 'Cancelled' WHERE FLIGHT_STATUS = 'Delayed';
DELETE FROM AIRLINE_DWH.CORE.FLIGHTS_HISTORY_DEMO WHERE TICKET_TYPE = 'Economy';
SELECT * FROM AIRLINE_DWH.CORE.FLIGHTS_HISTORY_DEMO AT(OFFSET => -60*5);
DROP TABLE AIRLINE_DWH.CORE.FLIGHTS_HISTORY_DEMO;
UNDROP TABLE AIRLINE_DWH.CORE.FLIGHTS_HISTORY_DEMO;

USE SCHEMA AIRLINE_DWH.CORE;

CREATE OR REPLACE ROW ACCESS POLICY COUNTRY_ACCESS_POLICY AS (country_val VARCHAR) RETURNS BOOLEAN ->
  CASE
    WHEN CURRENT_ROLE() = 'ACCOUNTADMIN' THEN TRUE
    WHEN CURRENT_ROLE() = 'ANALYST_US' AND country_val = 'United States' THEN TRUE
    ELSE FALSE
  END;

CREATE OR REPLACE VIEW AIRLINE_DWH.MARTS.SECURE_FLIGHTS_VIEW AS
SELECT f.*, a.COUNTRY_NAME
FROM AIRLINE_DWH.CORE.FLIGHTS f
JOIN AIRLINE_DWH.CORE.AIRPORTS a ON f.AIRPORT_ID = a.AIRPORT_ID;

ALTER VIEW AIRLINE_DWH.MARTS.SECURE_FLIGHTS_VIEW
ALTER COLUMN COUNTRY_NAME SET POLICY COUNTRY_ACCESS_POLICY;